#!/usr/bin/env ruby
$LOAD_PATH.unshift File.expand_path('../lib', __FILE__)
require 'cannon_rabbit'

game = CannonRabbit::Game.new(STDOUT)

game.start
tries = 0;

loop do
  puts "choose your firing angle (in degrees)"
  puts "bad luck, try again" unless tries == 0
  alpha = gets.chomp
  alpha = Float alpha rescue (alpha = nil)

  if alpha && (alpha > 0 && alpha < 360)
    tries = tries + 1
    game.cannon.fires(alpha)

    break if game.did_we_get_the_rabbit?
    game.rabbit.next_move
  else
    puts "make sure you give an number in degrees, that means between 0 to 360"
  end
end

game.success_message(tries)